### ISSUE TITLE
What is Streams?

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/IBMStreams.github.io#7]
Add statement about what Streams is.
There are different ways to present this information.

e.g. banner at the bottom.  

We may need to rework the text to make it fit better to the messages that we are trying to convey.

**Comment by hildrum** [comment]
Most projects place their "_____ is..." sentence near the top of their page. 
As a starting point for the wording discussion, consider  "Streams is a platform for distributed, efficient, fault-tolerant, real-time computation."

**Comment by scotts** [comment]
A "Streams is" sentence needs to be at the top, and visible before any other content. I think looking at examples from other projects is instructive:
- https://www.python.org/
- https://www.ruby-lang.org/en/
- http://www.perl.org/
- http://golang.org/
- http://www.rust-lang.org/
- http://fsharp.org/
- https://nodejs.org/
- https://www.docker.com/
- http://hhvm.com/
- http://clojure.org/
- http://bazel.io/

Most of these projects have a "X is" sentence visible at the top, in a promoted location along with the header graphics. Some have a longer paragraph or a section which explains what the project is, but it's still at the top, and likely to be the first thing readers see.

My recommended sentence is a small variation of @hildrum's: "Streams is a platform for distributed, fault-tolerant, efficient, real-time processing." However, I do think it's more important to put something up now, even if it's not perfect, and refine it later. Looking at some of the other projects, I actually think we should have an entire section, above "What's New" - people won't care about what's new until they know what it is. But that's a lot more work than a single sentence, which is very doable now.

**Comment by Alex-Cook4** [comment]
I agree that we need a "What is Streams?" statement. My concern with "Streams is a platform for distributed, fault-tolerant, efficient, real-time processing" is that it might be a bit intimidating for someone who doesn't know a ton about the Streaming sector and also might not be very accessible to someone without an engineering background. Our goal with this page was to minimize the amount of text and focus on giving people an image of what Streams could mean for them as a solution (Hence the videos in the Streams In Action section). We also want developers of all levels to feel like they can try Streams out pretty easily. On this page, we care more about "why" Streams, rather than "what." 

That being said, I think it's a good idea for us to have a single sentence that defines what Streams is. I'll think about it more, but this is the best I've got so far: "IBM Streams is a platform for real-time analytics and data processing."

**Comment by hildrum** [comment]
For the one-sentence description, I think it's important to include "distributed".  

This may be a topic for a different issue, but if you want developers to feel like they can try out Streams pretty easily, I think it should show code, either SPL or TStreams.  If you want to emphasize the drag and drop interface, show screen shots of that instead.    Maybe, in our case, something showing the programming model (operators and streams) would work as well.  Python, Ruby and Rust have code right up at the top.   

ETA: I'd be happy to see Alex's sentence go up as-is.

**Comment by scotts** [comment]
People don't care about "why" until they know what we're talking about. At the moment, we dive immediately into Scala support, MLib toolkit and Bluemix without ever having stated what is it we're talking about.

I have lots of opinions on what we should say, but "IBM Streams is a platform for real-time analytics and data processing" is a great start, and better than (literally) nothing. If we all agree that that sentence is better than nothing, then we should put it up now, and discuss how to refine it later.

**Comment by scotts** [comment]
Are we going to resolve this issue?

**Comment by chanskw** [comment]
Yes.. we will. Sorry for the delay. 

We are looking at the website again, and will incorporate this as part of that review.
